service: rest-with-serverless

provider:
  name: aws
  runtime: nodejs20.x

functions:
  getForecast:
    handler: index.handler
    events:
      - http:
          path: getForecastFunction
          method: get